- name: configure backend server
  hosts: backend
  become: yes
  vars:
    login_host: db.sivakumar.cloud
    login_password: ExpenseApp@1
  tasks:
  - name: disable default NodeJS
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enable NodeJS:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: Install NodeJS and MySQL
    ansible.builtin.dnf: 
      name: "{{ item }}"
      state: installed
    loop: 
    - nodejs
    - mysql

  - name: create user expense
    ansible.builtin.user:
      name: expense

