- name: configure the Frontend server
  become: yes
  hosts: frontend
  tasks:
  - name: Installation of nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: Enable the nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes